#!/bin/bash

# Convenience variable to the cred path
CREDENTIALS="${AWS_PATH}/credentials/example"

# No CloudFormation (perhaps)
unset AWS_CREDENTIAL_FILE

export AWS_ACCESS_KEY_ID="foo"
export AWS_SECRET_ACCESS_KEY="bar"
export EC2_PRIVATE_KEY="${CREDENTIALS}/pk.pem"
export EC2_CERT="${CREDENTIALS}/cert.pem"
