tap "goreleaser/tap"
tap "heroku/brew"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "osgeo/osgeo4mac"

brew "bats-core"
brew "cassandra"
brew "ctop"
brew "dep"
brew "envchain"
brew "ffmpeg"
brew "git"
brew "gnupg"
brew "goenv"
brew "gomplate"
brew "jq"
brew "kubernetes-helm"
brew "macvim"
brew "mas"
brew "mercurial"
brew "protobuf"
brew "mosh"
brew "mysql"
brew "openapi-generator"
brew "packer"
brew "pinentry-mac"
brew "postgresql"
brew "pstree"
brew "python-yq"
brew "s3cmd"
brew "socat"
brew "swagger-codegen"
brew "tcpflow"
brew "telnet"
brew "terraform"
brew "the_silver_searcher"
brew "tree"
brew "vault"
brew "watch"
brew "watchman"
brew "wget"
brew "yarn"
brew "youtube-dl"
brew "goreleaser/tap/goreleaser"
brew "heroku/brew/heroku"
brew "osgeo/osgeo4mac/pyspatialite"

cask "1password"
cask "alfred"
cask "battle-net"
cask "discord"
cask "docker"
cask "dropbox"
cask "encryptme"
cask "evernote"
cask "fantastical"
cask "firefox"
cask "google-chrome"
cask "google-cloud-sdk"
cask "imageoptim"
cask "istat-menus"
cask "iterm2"
cask "kaleidoscope"
cask "keybase"
cask "licecap"
cask "microsoft-office"
cask "minikube"
cask "monodraw"
cask "ngrok"
cask "nomad"
cask "postgres"
cask "postico"
cask "postman"
cask "screenflow"
cask "sequel-pro"
cask "sketch"
cask "skype"
cask "slack"
cask "slate"
cask "spotify"
cask "steam"
cask "tableplus"
cask "typora"
cask "visual-studio-code"
cask "vlc"
cask "waltr"
cask "xquartz"
cask "zoomus"

mas "Annotate", id: 918207447
mas "Bear", id: 1091189122
mas "Keynote", id: 409183694
mas "Markdown Plus", id: 972585766
mas "Pixelmator", id: 407963104
mas "Spark", id: 1176895641
mas "Tweetbot", id: 557168941
mas "Xcode", id: 497799835
