tap "goreleaser/tap"
tap "heroku/brew"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "osgeo/osgeo4mac"
brew "azure-cli"
brew "bats-core"
brew "envchain"
brew "ffmpeg"
brew "git"
brew "gnupg"
brew "goenv"
brew "gomplate"
brew "jq"
brew "kubernetes-helm"
brew "macvim"
brew "mas"
brew "mercurial"
brew "protobuf"
brew "mosh"
brew "mysql", link: false
brew "nomad"
brew "pinentry-mac"
brew "pkg-config"
brew "postgresql"
brew "prototool"
brew "python-yq"
brew "s3cmd"
brew "socat"
brew "swagger-codegen"
brew "tcpflow"
brew "telnet"
brew "terraform"
brew "the_silver_searcher"
brew "tree"
brew "vault"
brew "watch"
brew "watchman"
brew "yarn"
brew "youtube-dl"
brew "goreleaser/tap/goreleaser"
brew "heroku/brew/heroku"
cask "1password"
cask "alfred"
cask "battle-net"
cask "discord"
cask "docker"
cask "dropbox"
cask "fantastical"
cask "firefox"
cask "google-chrome"
cask "google-cloud-sdk"
cask "imageoptim"
cask "istat-menus"
cask "iterm2"
cask "java"
cask "kaleidoscope"
cask "keybase"
cask "licecap"
cask "microsoft-office"
cask "minikube"
cask "monodraw"
cask "ngrok"
cask "postgres"
cask "postico"
cask "screenflow"
cask "sketch"
cask "skype"
cask "slack"
cask "slate"
cask "spotify"
cask "steam"
cask "tableplus"
cask "typora"
cask "vlc"
cask "zoomus"
mas "Affinity Designer", id: 824171161
mas "Annotate", id: 918207447
mas "Bear", id: 1091189122
mas "Keynote", id: 409183694
mas "Markdown Plus", id: 972585766
mas "Pixelmator", id: 407963104
mas "Spark", id: 1176895641
mas "The Unarchiver", id: 425424353
mas "Things", id: 904280696
mas "Tweetbot", id: 557168941
mas "Xcode", id: 497799835
