#!/bin/bash
#
# This checks if go has been installed and adds it to the path
# if it has.

export GOPATH="$HOME/code/go"
export GOROOT_BOOTSTRAP="$HOME/go-bootstrap"
mkdir -p $GOPATH
export PATH="${GOPATH}/bin:$PATH"

if [[ -d "$HOME/go" ]]; then
    export GOROOT="$HOME/go"
    test -d ${GOROOT} &&
        export PATH="${GOROOT}/bin:$PATH"
fi

if [[ -d "$HOME/code/3rdparty/go" ]]; then
    export GOROOT="$HOME/code/3rdparty/go"
    test -d ${GOROOT} &&
        export PATH="${GOROOT}/bin:$PATH"
fi

case $UNAME in
    CYGWIN*)
        # In Cygwin, make sure that paths are real Windows paths
        GOPATH="$(cygpath -w $GOPATH)"
        GOROOT="$(cygpath -w $GOROOT)"
        ;;
esac

# Configure our private repositories. We just blacklist all of my personal
# and work GitHub to make this easy.

export GOPRIVATE="github.com/mitchellh,github.com/hashicorp"
