#!/bin/bash
#
# This checks if go has been installed and adds it to the path
# if it has.

export GOPATH="$HOME/code/go"
mkdir -p $GOPATH
export PATH="${GOPATH}/bin:$PATH"

if [[ -d "$HOME/go" ]]; then
    export GOROOT="$HOME/go"
    test -d ${GOROOT} &&
        export PATH="${GOROOT}/bin:$PATH"
fi

if [[ -d "$HOME/code/3rdparty/go" ]]; then
    export GOROOT="$HOME/code/3rdparty/go"
    test -d ${GOROOT} &&
        export PATH="${GOROOT}/bin:$PATH"
fi
