#!/bin/bash

# We only want to run this script on Linux
if [[ `uname` != "Linux" ]]; then
    return
fi

# Keybase setup
if [ -x "$(command -v keybase)" -a -x "$(command -v jq)" ]; then
    # If keybase isn't running, start it, or attempt to at least
    if [ `keybase status -j | jq '.KBFS.Running'` != 'true' ]; then
        KEYBASE_NO_SQUIRREL=1 run_keybase >/dev/null 2>&1
    fi
fi
