#!/bin/bash
#
# This script initializes the dev server.

SCRIPT_NAME="$(basename ${BASH_SOURCE[0]})"
pushd $(dirname ${BASH_SOURCE[0]}) >/dev/null
SCRIPT_DIR=$(pwd)
popd >/dev/null

source "${SCRIPT_DIR}/_functions.sh"

if ! is_devserver; then
    err "This script can only be called on a remote dev machine."
    exit 1
fi

if [ `keybase status -j | jq '.LoggedIn'` == 'true' ]; then
    status "Purging Keybase data..."
    keybase device remove --force-self $(keybase status -j | jq -r '.Device.name')
fi

status "Shredding SSH keys..."
shred -z -u -n100 $HOME/.ssh/*

success "Machine is wiped and clear to destroy."
